version: '3'
services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports: [5432]

  redis:
    image: redis:5.0-alpine
    ports: [6379]

  rabbitmq:
    image: rabbitmq:3.7-management
    ports: [5672, 15672]
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
